# -*- coding: utf-8 -*-
"""ablated_injury_severity_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLwxSop-Q2ehXNb2pb3nFMu3IbPi1asI
"""

# ============================================================
# NBA Injury Severity Classification
# Ablated-only fixed-split pipeline
#
# Files expected:
#   - split_train.csv
#   - split_dev.csv
#   - split_test.csv
#
# Models:
#   - Multinomial Naive Bayes
#   - Logistic Regression
#
# Setting:
#   - ablated_text only
#
# Outputs:
#   - ablated_model_results_summary.csv
#   - ablated_confusion_matrices_long.csv
#   - ablated_top_lr_features.csv
# ============================================================

import re
import json
import numpy as np
import pandas as pd

from itertools import product
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    accuracy_score,
    precision_recall_fscore_support,
)
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression


# ============================================================
# 1. CONFIG
# ============================================================

TRAIN_PATH = "split_train.csv"
DEV_PATH = "split_dev.csv"
TEST_PATH = "split_test.csv"

VALID_LABELS = ["MINOR", "MODERATE", "SEVERE"]
RANDOM_STATE = 42

LEAKAGE_PATTERNS = [
    # minor-style cues
    r"\bdtd\b",
    r"\bday[\s-]?to[\s-]?day\b",
    r"\bsoreness\b",
    r"\bsore\b",
    r"\btightness\b",
    r"\bstiffness\b",
    r"\billness\b",
    r"\bflu\b",
    r"\bspasm\b",
    r"\bspasms\b",
    r"\bdnp\b",

    # moderate-style cues
    r"\bsprain\b",
    r"\bsprained\b",
    r"\bstrain\b",
    r"\bstrained\b",
    r"\bfracture\b",
    r"\bfractured\b",
    r"\bbroken\b",
    r"\bbruise\b",
    r"\bbruised\b",
    r"\bcontusion\b",

    # severe-style cues
    r"\bacl\b",
    r"\bachilles\b",
    r"\btear\b",
    r"\btorn\b",
    r"\brupture\b",
    r"\bdislocation\b",
    r"\bdislocated\b",
    r"\bsurgery\b",
    r"\bout for season\b",
    r"\bout indefinitely\b",
    r"\bindefinitely\b",
    r"\bout\b",

    # roster-status artifacts
    r"\bplaced on il\b",
    r"\bon il\b",
    r"\bil\b",

    # side/location artifacts
    r"\bleft\b",
    r"\bright\b",
]

LEAKAGE_REGEX = re.compile("|".join(LEAKAGE_PATTERNS), flags=re.IGNORECASE)

LR_PARAM_GRID = {
    "ngram_range": [(1, 1), (1, 2)],
    "min_df": [1, 2, 5],
    "max_df": [0.95, 0.98],
    "C": [0.1, 1.0, 3.0, 10.0],
    "class_weight": [None, "balanced"],
}

NB_PARAM_GRID = {
    "ngram_range": [(1, 1), (1, 2)],
    "min_df": [1, 2, 5],
    "max_df": [0.95, 0.98],
    "alpha": [0.25, 0.5, 1.0],
}


# ============================================================
# 2. HELPERS
# ============================================================

def print_header(title: str) -> None:
    print("\n" + "=" * 78)
    print(title)
    print("=" * 78)


def normalize_text(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r"[/\-]", " ", text)
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def remove_leakage_terms(text: str) -> str:
    text = normalize_text(text)
    text = LEAKAGE_REGEX.sub(" ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def load_and_prepare_split(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)

    required_cols = ["input_text", "severity"]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"{path} is missing required columns: {missing}")

    df = df.copy()
    df["severity"] = df["severity"].astype(str).str.strip().str.upper()
    df = df[df["severity"].isin(VALID_LABELS)].copy()
    df["model_text"] = df["input_text"].fillna("").astype(str).apply(remove_leakage_terms)

    return df


def show_sample_ablation(df: pd.DataFrame, n: int = 6) -> None:
    print_header("Sample Ablated Rows")
    sample = df.head(n).copy()
    for i, row in sample.iterrows():
        print(f"\nRow {i}")
        print("Original:", row["input_text"])
        print("Ablated: ", row["model_text"])


def build_vectorizer(ngram_range=(1, 2), min_df=2, max_df=0.98):
    return TfidfVectorizer(
        ngram_range=ngram_range,
        min_df=min_df,
        max_df=max_df,
        sublinear_tf=True,
    )


def evaluate_predictions(y_true, y_pred) -> dict:
    macro_f1 = f1_score(y_true, y_pred, average="macro")
    weighted_f1 = f1_score(y_true, y_pred, average="weighted")
    acc = accuracy_score(y_true, y_pred)

    prec, rec, f1s, supports = precision_recall_fscore_support(
        y_true,
        y_pred,
        labels=VALID_LABELS,
        zero_division=0
    )

    return {
        "accuracy": acc,
        "macro_f1": macro_f1,
        "weighted_f1": weighted_f1,
        "precision_minor": prec[0],
        "recall_minor": rec[0],
        "f1_minor": f1s[0],
        "support_minor": supports[0],
        "precision_moderate": prec[1],
        "recall_moderate": rec[1],
        "f1_moderate": f1s[1],
        "support_moderate": supports[1],
        "precision_severe": prec[2],
        "recall_severe": rec[2],
        "f1_severe": f1s[2],
        "support_severe": supports[2],
    }


def confusion_to_long_df(y_true, y_pred, model_name, split_name):
    cm = confusion_matrix(y_true, y_pred, labels=VALID_LABELS)
    rows = []
    for i, true_label in enumerate(VALID_LABELS):
        for j, pred_label in enumerate(VALID_LABELS):
            rows.append({
                "model": model_name,
                "split": split_name,
                "true_label": true_label,
                "pred_label": pred_label,
                "count": int(cm[i, j]),
            })
    return pd.DataFrame(rows)


def print_eval_block(title: str, y_true, y_pred):
    print_header(title)
    metrics = evaluate_predictions(y_true, y_pred)
    print(f"Accuracy:  {metrics['accuracy']:.4f}")
    print(f"Macro F1:  {metrics['macro_f1']:.4f}")
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, digits=4, zero_division=0))
    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred, labels=VALID_LABELS))


# ============================================================
# 3. MODEL TUNING
# ============================================================

def tune_nb(X_train_text, y_train, X_dev_text, y_dev):
    best = None
    all_rows = []

    keys = list(NB_PARAM_GRID.keys())
    values = [NB_PARAM_GRID[k] for k in keys]

    for combo in product(*values):
        params = dict(zip(keys, combo))

        vectorizer = build_vectorizer(
            ngram_range=params["ngram_range"],
            min_df=params["min_df"],
            max_df=params["max_df"],
        )

        X_train_vec = vectorizer.fit_transform(X_train_text)
        X_dev_vec = vectorizer.transform(X_dev_text)

        clf = MultinomialNB(alpha=params["alpha"])
        clf.fit(X_train_vec, y_train)
        dev_preds = clf.predict(X_dev_vec)

        metrics = evaluate_predictions(y_dev, dev_preds)
        row = {
            "model": "MultinomialNB",
            **params,
            **metrics,
        }
        all_rows.append(row)

        if best is None or metrics["macro_f1"] > best["dev_macro_f1"]:
            best = {
                "vectorizer": vectorizer,
                "clf": clf,
                "params": params,
                "dev_preds": dev_preds,
                "dev_macro_f1": metrics["macro_f1"],
                "dev_metrics": metrics,
            }

    return best, pd.DataFrame(all_rows)


def tune_lr(X_train_text, y_train, X_dev_text, y_dev):
    best = None
    all_rows = []

    keys = list(LR_PARAM_GRID.keys())
    values = [LR_PARAM_GRID[k] for k in keys]

    for combo in product(*values):
        params = dict(zip(keys, combo))

        vectorizer = build_vectorizer(
            ngram_range=params["ngram_range"],
            min_df=params["min_df"],
            max_df=params["max_df"],
        )

        X_train_vec = vectorizer.fit_transform(X_train_text)
        X_dev_vec = vectorizer.transform(X_dev_text)

        clf = LogisticRegression(
            C=params["C"],
            class_weight=params["class_weight"],
            max_iter=4000,
            solver="lbfgs",
            random_state=RANDOM_STATE,
        )

        clf.fit(X_train_vec, y_train)
        dev_preds = clf.predict(X_dev_vec)

        metrics = evaluate_predictions(y_dev, dev_preds)
        row = {
            "model": "LogisticRegression",
            **params,
            **metrics,
        }
        all_rows.append(row)

        if best is None or metrics["macro_f1"] > best["dev_macro_f1"]:
            best = {
                "vectorizer": vectorizer,
                "clf": clf,
                "params": params,
                "dev_preds": dev_preds,
                "dev_macro_f1": metrics["macro_f1"],
                "dev_metrics": metrics,
            }

    return best, pd.DataFrame(all_rows)


def refit_and_test(vectorizer_params, model_name, model_params,
                   X_train_text, y_train, X_dev_text, y_dev, X_test_text):
    X_train_dev_text = pd.concat([X_train_text, X_dev_text], axis=0)
    y_train_dev = pd.concat([y_train, y_dev], axis=0)

    vectorizer = build_vectorizer(
        ngram_range=vectorizer_params["ngram_range"],
        min_df=vectorizer_params["min_df"],
        max_df=vectorizer_params["max_df"],
    )

    X_train_dev_vec = vectorizer.fit_transform(X_train_dev_text)
    X_test_vec = vectorizer.transform(X_test_text)

    if model_name == "MultinomialNB":
        clf = MultinomialNB(alpha=model_params["alpha"])
    elif model_name == "LogisticRegression":
        clf = LogisticRegression(
            C=model_params["C"],
            class_weight=model_params["class_weight"],
            max_iter=4000,
            solver="lbfgs",
            random_state=RANDOM_STATE,
        )
    else:
        raise ValueError(f"Unknown model_name: {model_name}")

    clf.fit(X_train_dev_vec, y_train_dev)
    test_preds = clf.predict(X_test_vec)

    return vectorizer, clf, test_preds


def extract_top_lr_features(vectorizer, clf, top_n=25):
    feature_names = vectorizer.get_feature_names_out()
    coef_matrix = clf.coef_
    classes = clf.classes_

    rows = []
    for i, class_label in enumerate(classes):
        top_idx = np.argsort(coef_matrix[i])[-top_n:][::-1]
        for rank, idx in enumerate(top_idx, start=1):
            rows.append({
                "class": class_label,
                "rank": rank,
                "feature": feature_names[idx],
                "coefficient": float(coef_matrix[i][idx]),
            })
    return pd.DataFrame(rows)


# ============================================================
# 4. LOAD ABLATED DATA
# ============================================================

train_df = load_and_prepare_split(TRAIN_PATH)
dev_df = load_and_prepare_split(DEV_PATH)
test_df = load_and_prepare_split(TEST_PATH)

print_header("Loaded Split Shapes")
print("Train:", train_df.shape)
print("Dev:  ", dev_df.shape)
print("Test: ", test_df.shape)

print_header("Columns")
print(train_df.columns.tolist())

show_sample_ablation(train_df, n=6)

print_header("Severity Distribution by Split")
print("Train:")
print(train_df["severity"].value_counts())
print("\nDev:")
print(dev_df["severity"].value_counts())
print("\nTest:")
print(test_df["severity"].value_counts())

X_train = train_df["model_text"]
y_train = train_df["severity"]

X_dev = dev_df["model_text"]
y_dev = dev_df["severity"]

X_test = test_df["model_text"]
y_test = test_df["severity"]


# ============================================================
# 5. RUN NB + LR ONLY
# ============================================================

results_rows = []
cm_frames = []

# Tune NB
best_nb, nb_grid_df = tune_nb(X_train, y_train, X_dev, y_dev)
nb_dev_preds = best_nb["dev_preds"]
print_eval_block("Ablated | Best MultinomialNB (DEV)", y_dev, nb_dev_preds)

results_rows.append({
    "model": "MultinomialNB",
    "split": "dev",
    "selected": False,
    "params_json": json.dumps(best_nb["params"]),
    **best_nb["dev_metrics"]
})
cm_frames.append(confusion_to_long_df(y_dev, nb_dev_preds, "MultinomialNB", "dev"))

# Tune LR
best_lr, lr_grid_df = tune_lr(X_train, y_train, X_dev, y_dev)
lr_dev_preds = best_lr["dev_preds"]
print_eval_block("Ablated | Best LogisticRegression (DEV)", y_dev, lr_dev_preds)

results_rows.append({
    "model": "LogisticRegression",
    "split": "dev",
    "selected": False,
    "params_json": json.dumps(best_lr["params"]),
    **best_lr["dev_metrics"]
})
cm_frames.append(confusion_to_long_df(y_dev, lr_dev_preds, "LogisticRegression", "dev"))

# Select between NB and LR
if best_lr["dev_macro_f1"] >= best_nb["dev_macro_f1"]:
    chosen_model = "LogisticRegression"
    chosen = best_lr
else:
    chosen_model = "MultinomialNB"
    chosen = best_nb

print_header("Selected model based on DEV")
print(chosen_model)
print("Params:", chosen["params"])
print(f"Dev Macro F1: {chosen['dev_macro_f1']:.4f}")

for row in results_rows[::-1]:
    if row["split"] == "dev" and row["model"] == chosen_model:
        row["selected"] = True
        break

# Final test on selected model
vec_params = {
    "ngram_range": chosen["params"]["ngram_range"],
    "min_df": chosen["params"]["min_df"],
    "max_df": chosen["params"]["max_df"],
}
model_params = chosen["params"].copy()

final_vectorizer, final_clf, test_preds = refit_and_test(
    vectorizer_params=vec_params,
    model_name=chosen_model,
    model_params=model_params,
    X_train_text=X_train,
    y_train=y_train,
    X_dev_text=X_dev,
    y_dev=y_dev,
    X_test_text=X_test,
)

print_eval_block(f"Ablated | Final {chosen_model} (TEST)", y_test, test_preds)

test_metrics = evaluate_predictions(y_test, test_preds)
results_rows.append({
    "model": chosen_model,
    "split": "test",
    "selected": True,
    "params_json": json.dumps(chosen["params"]),
    **test_metrics
})
cm_frames.append(confusion_to_long_df(y_test, test_preds, chosen_model, "test"))


# ============================================================
# 6. SAVE OUTPUTS
# ============================================================

results_df = pd.DataFrame(results_rows)
cm_df = pd.concat(cm_frames, ignore_index=True)

nb_grid_df.to_csv("ablated_nb_tuning_grid.csv", index=False)
lr_grid_df.to_csv("ablated_lr_tuning_grid.csv", index=False)
results_df.to_csv("ablated_model_results_summary.csv", index=False)
cm_df.to_csv("ablated_confusion_matrices_long.csv", index=False)

if chosen_model == "LogisticRegression":
    top_features_df = extract_top_lr_features(final_vectorizer, final_clf, top_n=25)
    top_features_df.to_csv("ablated_top_lr_features.csv", index=False)
else:
    top_features_df = pd.DataFrame(columns=["class", "rank", "feature", "coefficient"])
    top_features_df.to_csv("ablated_top_lr_features.csv", index=False)

print_header("Saved Files")
print("ablated_nb_tuning_grid.csv")
print("ablated_lr_tuning_grid.csv")
print("ablated_model_results_summary.csv")
print("ablated_confusion_matrices_long.csv")
print("ablated_top_lr_features.csv")


# ============================================================
# 7. FINAL SUMMARY
# ============================================================

print_header("Final Compact Summary")

summary_cols = [
    "model", "split", "selected",
    "accuracy", "macro_f1", "weighted_f1",
    "f1_minor", "f1_moderate", "f1_severe"
]

print(
    results_df[summary_cols]
    .sort_values(["split", "selected", "macro_f1"], ascending=[True, False, False])
    .to_string(index=False)
)